### ISSUE TITLE
HTTPError

### ISSUE THREAD

**Issue by GuillermoPena** [iamtraction/google-translate#26]
Something has changed...
It was working ok but now, the simplest example is failing with HTTPError...

**Comment by iamtraction** [comment]
Can you give a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by Ilyahas** [comment]
Just trying to run example and get this

**Comment by Ilyahas** [comment]
I think it depends on your computer.
I logged url that you send request :
'https://translate.google.com/translate_a/single?client=gtx&sl=auto&tl=uk&hl=uk&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0&TypeError='
'

and got  this

'Our systems have detected unusual traffic from your computer network. Please try to submit your request again later. Why did this happen?'

**Comment by Ilyahas** [comment]
and after few tries it starts working again.
maybe smth in token generator?

**Comment by iamtraction** [comment]
> Our systems have detected unusual traffic from your computer network. Please try to submit your request again later. Why did this happen?

That's a rate limit error. That means you're making more requests than you're allowed to.
