### ISSUE TITLE
When I try to translate "says goooo" and "Naguará me moría", I get TypeError

### ISSUE THREAD

**Issue by thawon** [iamtraction/google-translate#36]
Hi there,

When I try to translate "says goooo" and "Naguará me moría", I get TypeError. 

The error details is below:
"TypeError: Cannot read property 'forEach' of null\n    at translate (/app/node_modules/@iamtraction/google-translate/src/index.js:108:17)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"

I am able to reproduce the error every time I try to translate "says goooo" and "Naguará me moría"

As I look further into the investigate, I found that the same thing happens on Google Translate as well:
Google Translate when on the "DETECT LANGUAGE" mode, it is unable to recognize "says goooo" therefore, it return the result  as blank. 

Now, I just wondered why we have encounter this issue before. Did Google Translate has recently updated?

Regards,

**Comment by iamtraction** [comment]
it's working for me in the latest version of the library. try with it and feel free to reopen the issue if you're still facing the issue.
