### ISSUE TITLE
When translate long text. The version 2.0.0 give SyntaxError: Unexpected token '<', \"<html lang\"... is not valid JSON

### ISSUE THREAD

**Issue by thawon** [iamtraction/google-translate#43]
Hi there,

The version 2.0.0 errors out when trying to translate long text. The error is the following:
"SyntaxError: Unexpected token '<', \"<html lang\"... is not valid JSON"

The length of the text varies. On some English texts, it can translate up to 1380 characters but another error out at about 1200 characters. The error also happens in another language. For example: Chinese (zh-CN)  errors out at 400 characters.
(If you need me to give you the text I used to test this. I will be more than happy to. Because posting it here will be really unattractively long.)

Note: I've tried the same texts with the previous version (1.1.2) and it works just fine. So I guess the error has not got anything to do with the Google Translation Service.  

Many thanks :D

**Comment by iamtraction** [comment]
Can you give the texts that worked in earlier versions but is failing now?

**Comment by iamtraction** [comment]
Related #42

**Comment by iamtraction** [comment]
Fixed in [v2.0.1](https://github.com/iamtraction/google-translate/releases/tag/v2.0.1)
